<script>
  import FAQItem from "../components/FAQItem.svelte";
  import Link from "../components/Link.svelte";

  let tocItems = [];

  function addToToc(id, name) {
    tocItems = [...tocItems, {id, name}];
  }
</script>

<svelte:head>
  <title>open-diffix - Frequently asked questions</title>
</svelte:head>

<header class="max-w-2xl pt-28 mx-auto transition-all duration-500">
  <a id="faq-top">
    <h1 class="block text-6xl font-semibold w-100">
      Questions and answers
    </h1>
  </a>
</header>

<div class="max-w-2xl mx-auto mt-16 mb-12">
  <h2 class="block text-2xl w-100 font-semibold">
    Table of contents
  </h2>

  <ul class="mt-4 space-y-1.5 text-sm list-disc list-inside">
    {#each tocItems as question (question.id)}
      <li>
        <Link href="#{question.id}">{question.name}</Link>
      </li>
    {/each}
  </ul>
</div>

<FAQItem {addToToc} question="What is Open Diffix?">
  Open Diffix is a PostgreSQL extension for strong dynamic anonymization.
  It enables you to query your PostgreSQL database (nearly) as you’re used to,
  but makes sure you receive fully anonymous output. By "anonymous", we mean GDPR-level anonymous,
  meaning the results can’t be tied back to individuals, even if you have external information or
  you know how the anonymization process works in detail.
</FAQItem>

<FAQItem {addToToc} question="How does Open Diffix work?">
  Open Diffix is based on Diffix, the anonymization approach developed by Aircloak and the
  Max Planck Institute for Software Systems. Diffix takes ideas from tried and tested anonymization techniques,
  combines them in a smart and solution oriented way, and adds some proprietary protections on top.
  <!--  See here for our papers on the technology.-->
</FAQItem>

<FAQItem {addToToc} question="Does Open Diffix work for my use case X?">
  Because of the dynamic nature of the anonymization provided, certain use cases make more sense than others.

  Some use cases that are more likely to work well:

  <ul class="mt-2 mb-4 list-disc list-inside">
    <li>Descriptive and diagnostic analytics</li>
    <li>Business intelligence</li>
    <li>Dynamic or static reports and dashboards</li>
  </ul>

  Some use cases that Open Diffix was not built for and where you should expect unsatisfactory results:

  <ul class="mt-2 list-disc list-inside">
    <li>Prescriptive analytics</li>
    <li>Training machine learning algorithms</li>
    <li>Test data generation</li>
    <li>Data masking</li>
    <li>Pseudonymization</li>
  </ul>
</FAQItem>

<FAQItem {addToToc} question="Does Open Diffix use Differential Privacy?">
  No. Diffix and Differential Privacy have many surface level likenesses
  (like distorting answers by adding noise), but fundamentally differ in their implementations.
  Crucially, Diffix does not have the concept of a privacy budget, which makes it much easier
  to use in real world scenarios, but in turn also does not offer mathematical guarantees.
  <!--  Please see here for our papers on the technology.-->
</FAQItem>

<FAQItem {addToToc} question="How do I use Open Diffix for my project / company?">
  At this point in time, you can’t use Open Diffix yet. When the time has come,
  you will be able to download an extension and install it in your PostgreSQL database.
  There will be a small setup step for datasets that you want to be able to query through the
  Open Diffix layer. Afterwards, you can work with the data as you’re used to.
</FAQItem>

<FAQItem {addToToc} question="I would like to try out Open Diffix. Where can I schedule a demo?">
  You don’t have to schedule anything – we will soon host a demo system of our very first version for you to test.
  Please note that this is only a technical demo of Open Diffix Publish,
  with a highly restricted interface and without any privacy guarantees.
  Check back later for newer versions.
</FAQItem>

<FAQItem {addToToc} question="What is Open Diffix “Publish”?">
  We are currently aiming at releasing Open Diffix in several steps, for several use cases.
  The first versions we’ll release are centered around what we call Open Diffix Publish.
  Publish is intended for use cases in which the analyst, i.e. the person running live queries,
  can be trusted to not try and attack the system (for instance because they are contractually bound,
  or have access to the raw data anyway, or because their interface doesn’t allow them to).
  It is therefore ideal for use cases in reports generated by trusted analysts or business
  intelligence dashboards that should still be anonymous and safe to share with anyone.
</FAQItem>

<FAQItem {addToToc} question="When will a full version be released? What will be the feature set of version X?">
  We do not release roadmaps or timelines. However, Open Diffix is a full time effort,
  and will definitely improve. The best early warning you can get is by
  <Link href="newsletter">signing up to our newsletter</Link>,
  where we share the newest developments and ask for beta signups.
</FAQItem>

<FAQItem {addToToc} question="Is Open Diffix GDPR compliant?">
  The intent is that you will be able to use Open Diffix in good conscience in the EU and
  anywhere in the world. We are trying to provide the highest level of anonymization.
  We will be working with national authorities to provide users with legal certainty where possible.
</FAQItem>

<FAQItem {addToToc} question="How does Open Diffix make money?">
  Open Diffix will be free to use for the vast majority of use cases. Since Open Diffix is not
  an organization or company as such, it does not necessarily have to generate money. However,
  in order to secure the longevity of the project and provide incentive for any sponsors,
  we are planning to charge for certain use cases. Equally, adapting the technology to other databases
  than PostgreSQL will only be possible with licenses we can provide.
</FAQItem>

<FAQItem {addToToc} question="Is Open Diffix Open Source?">
  No. For the moment, Open Diffix will not be Open Source in the sense of the Open Source Initiative definition.
  However, it will be “open code” or “code available” – meaning you will be able to view, adapt and copy the code,
  and the vast majority of use cases will be free to use.
</FAQItem>

<FAQItem {addToToc} question="Where can I see the Open Diffix code?">
  At this point in time, the code is not public yet. When it is, you will find a link to our github repository on our website.
</FAQItem>

<FAQItem {addToToc} question="I have a general question, who can I contact?">
  Please contact Felix at <Link href="mailto:felix@open-diffix.org">felix@open-diffix.org</Link>
  or visit our <Link href="https://github.com/diffix/pg_diffix_extension">Github repository</Link>
  to take part in the discussions there
</FAQItem>
